<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nodedb"
 *
 * Auto generated by Extension Builder 2016-09-23
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'nodedb',
	'description' => 'Node Database for Freifunk Augsburg.',
	'category' => 'plugin',
	'author' => 'Manuel Munz',
	'author_email' => 't3dev@comuno.net',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);